services:
  - type: web
    name: someone-v1-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
